
PyAutoFunction_RegisterVoid(setName, 1, String);
PyAutoFunction_Register(getName, String, 1, cons);
PyAutoFunction_Register(getNumFrameIDs, int, 0);
PyAutoFunction_Register(getFrameIDAtIndex, int, 1, unsigned);
PyAutoFunction_RegisterVoid(insertFrame, 2, unsigned, unsigned);
PyAutoFunction_Register(setNewFrameIDs, POLYIGNORE, 1, st);
PyAutoFunction_RegisterVoid(removeFrameByIndex, 1, unsigned);
PyAutoFunction_Register(removeFrameIndices, POLYIGNORE, 1, st);
PyAutoFunction_RegisterVoid(clearFrames, 0);
PyAutoFunction_RegisterVoid(setPixelsPerUnit, 1, Number);
PyAutoFunction_Register(getPixelsPerUnit, Number, 0);
PyAutoFunction_RegisterVoid(rebuildStateMeshes, 0);
PyAutoFunction_RegisterVoid(setStateFPS, 1, Number);
PyAutoFunction_Register(getStateFPS, Number, 0);
PyAutoFunction_Register(getLargestFrameBoundingBox, Vector3, 1, cons);
PyAutoFunction_Register(getBoundingBox, Vector2, 0);
PyAutoFunction_Register(getSpriteOffset, Vector2, 0);
PyAutoFunction_RegisterVoid(setSpriteOffset, 1, const);
PyAutoFunction_Register(getName, String, 0);
PyAutoFunction_RegisterVoid(setName, 1, String);
PyAutoFunction_RegisterVoid(addSpriteState, 1, SpriteStat);
PyAutoFunction_RegisterVoid(removeSpriteState, 1, SpriteStat);
PyAutoFunction_Register(getNumStates, int, 0);
PyAutoFunction_RegisterVoid(setParentSpritSet, 1, SpriteSe);
PyAutoFunction_RegisterVoid(setTexture, 1, Textur);
PyAutoFunction_RegisterVoid(addSpriteEntry, 1, Sprit);
PyAutoFunction_Register(getNumSpriteEntries, int, 1, cons);
PyAutoFunction_RegisterVoid(loadSpriteSet, 1, String);
PyAutoFunction_RegisterVoid(addSpriteFrame, 2, const, bool);
PyAutoFunction_Register(getNumFrames, int, 1, cons);
PyAutoFunction_RegisterVoid(setSpriteFrame, 1, const);
PyAutoFunction_RegisterVoid(clearFrames, 0);
PyAutoFunction_RegisterVoid(createGridFrames, 3, Number, Number, const);
PyAutoFunction_RegisterVoid(createFramesFromIslands, 2, unsigned, const);
PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
PyAutoFunction_RegisterVoid(handleEvent, 1, Even);
PyAutoFunction_RegisterVoid(setSpriteSet, 1, SpriteSe);
PyAutoFunction_RegisterVoid(setSpriteByName, 1, String);
PyAutoFunction_RegisterVoid(setCurrentFrame, 1, unsigned);
PyAutoFunction_Register(getCurrentFrame, int, 0);
PyAutoFunction_RegisterVoid(Update, 0);
PyAutoFunction_RegisterVoid(Render, 0);
PyAutoFunction_Register(getSpriteBoundingBox, Vector3, 1, cons);
PyAutoFunction_Register(isPaused, bool, 0);
PyAutoFunction_RegisterVoid(setSprite, 1, Sprit);
PyAutoFunction_RegisterVoid(setSpriteState, 3, SpriteStat, unsigned, bool);
PyAutoFunction_RegisterVoid(setSpriteStateByName, 3, String, unsigned, bool);
PyAutoFunction_Register(getStartOnRandomFrame, bool, 0);
PyAutoFunction_RegisterVoid(setStartOnRandomFrame, 1, bool);

