
PyAutoStruct_Register(Vector4_struct);
PyAutoStruct_RegisterMember(Vector4_struct, x, float);
PyAutoStruct_RegisterMember(Vector4_struct, y, float);
PyAutoStruct_RegisterMember(Vector4_struct, z, float);
PyAutoStruct_RegisterMember(Vector4_struct, w, float);

PyAutoStruct_Register(Vector3_struct);
PyAutoStruct_RegisterMember(Vector3_struct, x, float);
PyAutoStruct_RegisterMember(Vector3_struct, y, float);
PyAutoStruct_RegisterMember(Vector3_struct, z, float);

PyAutoStruct_Register(Vector2_struct);
PyAutoStruct_RegisterMember(Vector2_struct, x, float);
PyAutoStruct_RegisterMember(Vector2_struct, y, float);

PyAutoFunction_Register(getVertexCount, int, 10, cons, arrayDirtyMap, positio, norma, et, Mes, Mes, Mes, Mes, Mes);
PyAutoFunction_Register(Mesh, explicit, 1, const);
PyAutoFunction_RegisterVoid(loadMesh, 1, const);
PyAutoFunction_RegisterVoid(clearMesh, 0);
PyAutoFunction_RegisterVoid(saveToFile, 7, const, bool, bool, bool, bool, bool, bool);
PyAutoFunction_RegisterVoid(loadFromFile, 1, OSFIL);
PyAutoFunction_RegisterVoid(saveToFile, 7, OSFIL, bool, bool, bool, bool, bool, bool);
PyAutoFunction_Register(getVertexCount, int, 0);
PyAutoFunction_RegisterVoid(createPlane, 2, Number, Number);
PyAutoFunction_RegisterVoid(createVPlane, 2, Number, Number);
PyAutoFunction_RegisterVoid(createCircle, 3, Number, Number, unsigned);
PyAutoFunction_RegisterVoid(createLineCircle, 3, Number, Number, unsigned);
PyAutoFunction_RegisterVoid(createTorus, 4, Number, Number, int, int);
PyAutoFunction_RegisterVoid(createBox, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(createSphere, 3, Number, int, int);
PyAutoFunction_RegisterVoid(createIcosphere, 2, Number, int);
PyAutoFunction_RegisterVoid(createOctosphere, 2, Number, int);
PyAutoFunction_RegisterVoid(createCylinder, 4, Number, Number, int, bool);
PyAutoFunction_RegisterVoid(createCone, 3, Number, Number, int);
PyAutoFunction_Register(recenterMesh, Vector3, 0);
PyAutoFunction_RegisterVoid(setVertexAtOffset, 4, unsigned, Number, Number, Number);
PyAutoFunction_RegisterVoid(addVertexWithUVAndNormal, 8, Number, Number, Number, Number, Number, Number, Number, Number);
PyAutoFunction_RegisterVoid(addTexCoord, 2, Number, Number);
PyAutoFunction_RegisterVoid(addTexCoord2, 2, Number, Number);
PyAutoFunction_RegisterVoid(addTangent, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(addVertexWithUV, 5, Number, Number, Number, Number, Number);
PyAutoFunction_RegisterVoid(addVertex, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(addNormal, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(addNormal, 1, const);
PyAutoFunction_RegisterVoid(addBoneAssignments, 8, Number, unsigned, Number, unsigned, Number, unsigned, Number, unsigned);
PyAutoFunction_RegisterVoid(addColor, 4, Number, Number, Number, Number);
PyAutoFunction_RegisterVoid(addColor, 1, const);
PyAutoFunction_Register(getVertexPosition, Vector3, 1, unsigned);
PyAutoFunction_Register(getVertexPositionAtIndex, Vector3, 1, unsigned);
PyAutoFunction_Register(getVertexTexCoord, Vector2, 1, unsigned);
PyAutoFunction_Register(getVertexTexCoordAtIndex, Vector2, 1, unsigned);
PyAutoFunction_RegisterVoid(setVertexBuffer, 1, VertexBuffe);
PyAutoFunction_Register(getRadius, Number, 0);
PyAutoFunction_RegisterVoid(calculateNormals, 0);
PyAutoFunction_RegisterVoid(calculateTangents, 0);
PyAutoFunction_Register(getMeshType, int, 0);
PyAutoFunction_RegisterVoid(setMeshType, 1, int);
PyAutoFunction_Register(getIndexGroupSize, int, 1, switc);
PyAutoFunction_Register(hasVertexBuffer, bool, 3, return, the, unsigned);
PyAutoFunction_RegisterVoid(addIndexedFace, 3, unsigned, unsigned, unsigned);
PyAutoFunction_RegisterVoid(addIndexedFace, 4, unsigned, unsigned, unsigned, unsigned);
PyAutoFunction_RegisterVoid(addIndex, 1, unsigned);
PyAutoFunction_RegisterVoid(removeVertexRange, 2, unsigned, int);
PyAutoFunction_RegisterVoid(removeFace, 1, unsigned);
PyAutoFunction_Register(removeUnusedVertices, int, 0);
PyAutoFunction_Register(getIndexCount, int, 0);
PyAutoFunction_RegisterVoid(subdivideToRadius, 2, Number, int);
PyAutoFunction_Register(calculateFaceTangent, Vector3, 6, const, const, const, const, const, const);
PyAutoFunction_RegisterVoid(saveAsOBJ, 1, const);
PyAutoFunction_RegisterVoid(normalizeBoneWeights, 0);
PyAutoFunction_RegisterVoid(loadFromFileV2, 1, OSFIL);
PyAutoFunction_RegisterVoid(loadFromFileLegacyV1, 1, OSFIL);
PyAutoFunction_RegisterVoid(writeVertexBlock, 2, VertexDataArra, OSFIL);
PyAutoFunction_RegisterVoid(writeIndexBlock, 2, IndexDataArra, OSFIL);

