
PyAutoFunction_RegisterVoid(initEntity, 0);
PyAutoFunction_RegisterVoid(Render, 1, *);
PyAutoFunction_RegisterVoid(renderChildren, 0);
PyAutoFunction_Register(Clone, call, 4, on, bool, bool, bool);
PyAutoFunction_RegisterVoid(rebuildTransformMatrix, 0);
PyAutoFunction_RegisterVoid(updateEntityMatrix, 0);
PyAutoFunction_Register(getConcatenatedMatrix, Matrix4, 0);
PyAutoFunction_Register(getConcatenatedMatrixRelativeTo, Matrix4, 1, Entit);
PyAutoFunction_Register(getAnchorAdjustedMatrix, Matrix4, 0);
PyAutoFunction_Register(getConcatenatedMatrix, as, 2, but, without);
PyAutoFunction_Register(getLookAtMatrix, Matrix4, 2, const, const);
PyAutoFunction_RegisterVoid(addChild, 1, Entit);
PyAutoFunction_RegisterVoid(removeChild, 1, Entit);
PyAutoFunction_RegisterVoid(moveChildUp, 1, Entit);
PyAutoFunction_RegisterVoid(moveChildDown, 1, Entit);
PyAutoFunction_RegisterVoid(moveChildTop, 1, Entit);
PyAutoFunction_RegisterVoid(moveChildBottom, 1, Entit);
PyAutoFunction_RegisterVoid(setParentEntity, 1, Entit);
PyAutoFunction_Register(getNumChildren, int, 0);
PyAutoFunction_RegisterVoid(setOwnsChildrenRecursive, 1, bool);
PyAutoFunction_Register(getPosition, Vector3, 4, cons, use, Number, Number);
PyAutoFunction_RegisterVoid(setPosition, 1, const);
PyAutoFunction_RegisterVoid(setPositionX, 1, Number);
PyAutoFunction_RegisterVoid(setPositionY, 1, Number);
PyAutoFunction_RegisterVoid(Translate, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(Translate, 1, const);
PyAutoFunction_RegisterVoid(setPositionZ, 1, Number);
PyAutoFunction_RegisterVoid(setScaleX, 1, Number);
PyAutoFunction_RegisterVoid(setScaleY, 1, Number);
PyAutoFunction_RegisterVoid(setScaleZ, 1, Number);
PyAutoFunction_RegisterVoid(Scale, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(Scale, 1, const);
PyAutoFunction_RegisterVoid(setScale, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(setScale, 1, const);
PyAutoFunction_Register(getCompoundScale, Vector3, 1, cons);
PyAutoFunction_RegisterVoid(setRotationEuler, 1, const);
PyAutoFunction_RegisterVoid(setPitch, 1, Number);
PyAutoFunction_RegisterVoid(setYaw, 1, Number);
PyAutoFunction_RegisterVoid(setRoll, 1, Number);
PyAutoFunction_RegisterVoid(Roll, 1, Number);
PyAutoFunction_RegisterVoid(Yaw, 1, Number);
PyAutoFunction_RegisterVoid(Pitch, 1, Number);
PyAutoFunction_Register(getPitch, Number, 1, cons);
PyAutoFunction_RegisterVoid(setHeight, 1, Number);
PyAutoFunction_RegisterVoid(setDepth, 1, Number);
PyAutoFunction_RegisterVoid(setRotationQuat, 4, Number, Number, Number, Number);
PyAutoFunction_RegisterVoid(setRotationByQuaternion, 1, const);
PyAutoFunction_Register(getRotationQuat, Quaternion, 2, cons, const);
PyAutoFunction_Register(lookAt, see, 2, void, const);
PyAutoFunction_Register(getCombinedColor, Color, 4, cons, Number, Number, Number);
PyAutoFunction_RegisterVoid(setColorInt, 4, int, int, int, int);
PyAutoFunction_RegisterVoid(setColor, 1, Color);
PyAutoFunction_RegisterVoid(setAnchorPoint, 1, const);
PyAutoFunction_RegisterVoid(setAnchorPoint, 3, Number, Number, Number);
PyAutoFunction_Register(getAnchorPoint, Vector3, 3, cons, int, int);
PyAutoFunction_Register(onMouseUp, MouseEventResult, 3, const, int, int);
PyAutoFunction_Register(onMouseMove, MouseEventResult, 2, const, int);
PyAutoFunction_Register(onMouseWheelUp, MouseEventResult, 2, const, int);
PyAutoFunction_Register(onMouseWheelDown, MouseEventResult, 2, const, int);
PyAutoFunction_RegisterVoid(setUserData, 1, voi);
PyAutoFunction_RegisterVoid(setBlendingMode, 1, int);
PyAutoFunction_Register(getEntityProp, String, 1, const);
PyAutoFunction_RegisterVoid(setEntityProp, 2, const, const);
PyAutoFunction_RegisterVoid(setInverseY, 1, bool);
PyAutoFunction_Register(getInverseY, bool, 0);
PyAutoFunction_RegisterVoid(doUpdates, 0);
PyAutoFunction_RegisterVoid(doFixedUpdates, 0);
PyAutoFunction_Register(buildPositionMatrix, Matrix4, 0);
PyAutoFunction_RegisterVoid(setRenderer, 1, Rendere);
PyAutoFunction_Register(customHitDetection, bool, 5, const, the, will, this, false);
PyAutoFunction_RegisterVoid(addTag, 1, String);
PyAutoFunction_Register(getScreenPosition, Vector2, 3, const, const, const);
PyAutoFunction_Register(getScreenPositionForMainCamera, Vector2, 0);
PyAutoFunction_RegisterVoid(recalculateAABBAllChildren, 0);
PyAutoFunction_RegisterVoid(recalculateAABB, 0);
PyAutoFunction_Register(getWorldAABB, AABB, 0);
PyAutoFunction_Register(getLocalBoundingBox, Vector3, 0);
PyAutoFunction_RegisterVoid(setLocalBoundingBox, 1, const);
PyAutoFunction_RegisterVoid(setLocalBoundingBox, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(setLocalBoundingBoxX, 1, Number);
PyAutoFunction_RegisterVoid(setLocalBoundingBoxY, 1, Number);
PyAutoFunction_RegisterVoid(setLocalBoundingBoxZ, 1, Number);

