
PyAutoFunction_Register(operator, bool, 2, LightInfo, LightInfo);
PyAutoFunction_Register(Init, bool, 0);
PyAutoFunction_RegisterVoid(Resize, 2, int, int);
PyAutoFunction_RegisterVoid(EndRender, 0);
PyAutoFunction_RegisterVoid(destroyTexture, 6, Textur, Textur, int, int, bool, unsigned);
PyAutoFunction_RegisterVoid(bindFrameBufferTextureDepth, 1, Textur);
PyAutoFunction_RegisterVoid(unbindFramebuffers, 0);
PyAutoFunction_RegisterVoid(setViewportSize, 2, int, int);
PyAutoFunction_RegisterVoid(resetViewport, 8, virtual, Number, Number, Number, bool, Number, Number, Number);
PyAutoFunction_RegisterVoid(setClearColor, 1, Color);
PyAutoFunction_RegisterVoid(setAmbientColor, 3, Number, Number, Number);
PyAutoFunction_RegisterVoid(clearScreen, 16, bool, bool, Number, Number, Number, Number, IndexDataArra, Number, Number, Color, Number, Number, Number, ShaderBindin, unsigned, bool);
PyAutoFunction_RegisterVoid(clearShader, 2, virtual, bool);
PyAutoFunction_RegisterVoid(billboardMatrixWithScale, 1, Vector3);
PyAutoFunction_RegisterVoid(setTextureFilteringMode, 1, int);
PyAutoFunction_RegisterVoid(setProjectionFromFrustum, 11, Number, Number, Number, Number, Number, Number, Number, Number, drawn, they, bool);
PyAutoFunction_RegisterVoid(drawScreenQuad, 2, Number, Number);
PyAutoFunction_Register(getYRes, int, 0);
PyAutoFunction_Register(isScissorEnabled, bool, 0);
PyAutoFunction_RegisterVoid(enableScissor, 1, bool);
PyAutoFunction_RegisterVoid(setScissorBox, 1, Polycod);
PyAutoFunction_Register(getScissorBox, Rectangle, 0);
PyAutoFunction_RegisterVoid(setAnisotropyAmount, 1, Number);
PyAutoFunction_Register(getAnisotropyAmount, Number, 0);
PyAutoFunction_RegisterVoid(cullFrontFaces, 1, bool);
PyAutoFunction_RegisterVoid(addLight, 15, int, const, const, int, const, const, Number, Number, Number, Number, Number, Number, bool, Matrix, Textur);
PyAutoFunction_RegisterVoid(setExposureLevel, 1, Number);
PyAutoFunction_Register(projectRayFrom2DCoordinate, Vector3, 8, Number, Number, const, const, const, const, const, const);
PyAutoFunction_Register(getViewportWidth, Number, 0);
PyAutoFunction_Register(getViewportHeight, Number, 0);
PyAutoFunction_RegisterVoid(setViewportShift, 2, Number, Number);
PyAutoFunction_RegisterVoid(setRendererShaderParams, 2, Shade, ShaderBindin);
PyAutoFunction_RegisterVoid(addShaderModule, 1, PolycodeShaderModul);
PyAutoFunction_Register(getProjectionMatrix, Matrix4, 5, virtual, Number, const, const, const);
PyAutoFunction_Register(getNumPointLights, int, 2, return, Number);
PyAutoFunction_Register(getBackingResolutionScaleX, Number, 0);
PyAutoFunction_Register(getBackingResolutionScaleY, Number, 0);
PyAutoFunction_RegisterVoid(setOverrideMaterial, 1, Materia);
PyAutoFunction_RegisterVoid(pushVertexColor, 0);
PyAutoFunction_RegisterVoid(popVertexColor, 0);
PyAutoFunction_RegisterVoid(loadVertexColorIdentity, 0);
PyAutoFunction_RegisterVoid(multiplyVertexColor, 1, const);
PyAutoFunction_RegisterVoid(setRenderToGlobalFramebuffer, 1, bool);

