#include "./PyAutoC/Python27/include/Python.h"
#include "./PyAutoC/include/PyAutoC.h"

#include "../../../Core/Contents/Include/PolyBezierCurve.h"
#include "../../../Core/Contents/Include/PolyBone.h"
#include "../../../Core/Contents/Include/PolyCamera.h"
#include "../../../Core/Contents/Include/Polycode.h"
#include "../../../Core/Contents/Include/PolyColor.h"
#include "../../../Core/Contents/Include/PolyConfig.h"
#include "../../../Core/Contents/Include/PolyCore.h"
#include "../../../Core/Contents/Include/PolyCoreInput.h"
#include "../../../Core/Contents/Include/PolyCoreServices.h"
#include "../../../Core/Contents/Include/PolyCubemap.h"
#include "../../../Core/Contents/Include/PolyData.h"
#include "../../../Core/Contents/Include/PolyEntity.h"
#include "../../../Core/Contents/Include/PolyEvent.h"
#include "../../../Core/Contents/Include/PolyEventDispatcher.h"
#include "../../../Core/Contents/Include/PolyEventHandler.h"
#include "../../../Core/Contents/Include/PolyFixedShader.h"
#include "../../../Core/Contents/Include/PolyFont.h"
#include "../../../Core/Contents/Include/PolyFontManager.h"
#include "../../../Core/Contents/Include/PolyGLCubemap.h"
#include "../../../Core/Contents/Include/PolyGlobals.h"
#include "../../../Core/Contents/Include/PolyImage.h"
#include "../../../Core/Contents/Include/PolyInputEvent.h"
#include "../../../Core/Contents/Include/PolyInputKeys.h"
#include "../../../Core/Contents/Include/PolyLabel.h"
#include "../../../Core/Contents/Include/PolyMaterial.h"
#include "../../../Core/Contents/Include/PolyMaterialManager.h"
#include "../../../Core/Contents/Include/PolyMatrix4.h"
#include "../../../Core/Contents/Include/PolyMesh.h"
#include "../../../Core/Contents/Include/PolyModule.h"
#include "../../../Core/Contents/Include/PolyObject.h"
#include "../../../Core/Contents/Include/PolyParticleEmitter.h"
#include "../../../Core/Contents/Include/PolyPerlin.h"
#include "../../../Core/Contents/Include/PolyQuaternion.h"
#include "../../../Core/Contents/Include/PolyQuaternionCurve.h"
#include "../../../Core/Contents/Include/PolyRay.h"
#include "../../../Core/Contents/Include/PolyRectangle.h"
#include "../../../Core/Contents/Include/PolyRenderDataArray.h"
#include "../../../Core/Contents/Include/PolyRenderer.h"
#include "../../../Core/Contents/Include/PolyResource.h"
#include "../../../Core/Contents/Include/PolyResourceManager.h"
#include "../../../Core/Contents/Include/PolyScene.h"
#include "../../../Core/Contents/Include/PolySceneEntityInstance.h"
#include "../../../Core/Contents/Include/PolySceneImage.h"
#include "../../../Core/Contents/Include/PolySceneLabel.h"
#include "../../../Core/Contents/Include/PolySceneLight.h"
#include "../../../Core/Contents/Include/PolySceneLine.h"
#include "../../../Core/Contents/Include/PolySceneManager.h"
#include "../../../Core/Contents/Include/PolySceneMesh.h"
#include "../../../Core/Contents/Include/PolyScenePrimitive.h"
#include "../../../Core/Contents/Include/PolySceneRenderTexture.h"
#include "../../../Core/Contents/Include/PolySceneSound.h"
#include "../../../Core/Contents/Include/PolySceneSprite.h"
#include "../../../Core/Contents/Include/PolyShader.h"
#include "../../../Core/Contents/Include/PolySkeleton.h"
#include "../../../Core/Contents/Include/PolySound.h"
#include "../../../Core/Contents/Include/PolySoundManager.h"
#include "../../../Core/Contents/Include/PolyString.h"
#include "../../../Core/Contents/Include/PolyTextMesh.h"
#include "../../../Core/Contents/Include/PolyTexture.h"
#include "../../../Core/Contents/Include/PolyTimer.h"
#include "../../../Core/Contents/Include/PolyTimerManager.h"
#include "../../../Core/Contents/Include/PolyVector2.h"
#include "../../../Core/Contents/Include/PolyVector3.h"
#include "../../../Core/Contents/Include/PolyVector4.h"
#include "../../../Core/Contents/Include/rgbe.h"

int main(int argc, char **argv) {
	Py_Initialize();
	PyAutoC_Initialize();

	PyAutoFunction_Register(getNumControlPoints, int, 0);
	PyAutoFunction_Register(addControlPoint3dWithHandles, see, 9, void, Number, Number, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addControlPoint3dWithHandles, 9, Number, Number, Number, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addControlPoint3d, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addControlPoint2dWithHandles, 6, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addControlPoint2d, 2, Number, Number);
	PyAutoFunction_Register(getPointAt, Vector3, 1, Number);
	PyAutoFunction_Register(getPointBetween, Vector3, 3, Number, BezierPoin, BezierPoin);
	PyAutoFunction_RegisterVoid(clearControlPoints, 0);
	PyAutoFunction_Register(getYValueAtX, Number, 1, Number);
	PyAutoFunction_Register(getTValueAtX, Number, 1, Number);
	PyAutoFunction_RegisterVoid(removePoint, 1, BezierPoin);
	PyAutoFunction_RegisterVoid(setHeightCacheResolution, 1, Number);
	PyAutoFunction_RegisterVoid(rebuildHeightCache, 0);
	PyAutoFunction_RegisterVoid(recalculateDistances, 0);
	PyAutoFunction_Register(Bone, explicit, 1, const);
	PyAutoFunction_Register(getName, String, 1, cons);
	PyAutoFunction_RegisterVoid(addChildBone, 1, Bon);
	PyAutoFunction_Register(getParentBone, Bone*, 0);
	PyAutoFunction_Register(getNumChildBones, int, 0);
	PyAutoFunction_Register(getBoneMatrix, Matrix4, 1, cons);
	PyAutoFunction_Register(getRestMatrix, Matrix4, 1, cons);
	PyAutoFunction_RegisterVoid(setBaseMatrix, 1, const);
	PyAutoFunction_Register(getFullBaseMatrix, Matrix4, 1, cons);
	PyAutoFunction_Register(Camera, explicit, 1, Scen);
	PyAutoFunction_RegisterVoid(buildFrustumPlanes, 0);
	PyAutoFunction_Register(canSee, see, 2, bool, Number);
	PyAutoFunction_Register(isAABBInFrustum, bool, 1, const);
	PyAutoFunction_RegisterVoid(setOrthoMode, 1, bool);
	PyAutoFunction_RegisterVoid(setOrthoSize, 2, Number, Number);
	PyAutoFunction_RegisterVoid(setFrustumMode, 6, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_Register(getOrthoMode, bool, 1, return);
	PyAutoFunction_Register(getOrthoSizeY, Number, 0);
	PyAutoFunction_RegisterVoid(setFOV, 1, Number);
	PyAutoFunction_Register(getFOV, Number, 2, return, Number);
	PyAutoFunction_Register(getNearClippingPlane, Number, 0);
	PyAutoFunction_Register(getFarClippingPlane, Number, 0);
	PyAutoFunction_RegisterVoid(setParentScene, 1, Scen);
	PyAutoFunction_RegisterVoid(doCameraTransform, 0);
	PyAutoFunction_Register(hasFilterShader, bool, 0);
	PyAutoFunction_RegisterVoid(drawFilter, 5, Textur, Number, Number, Textur, Textur);
	PyAutoFunction_RegisterVoid(setExposureLevel, 1, Number);
	PyAutoFunction_RegisterVoid(setPostFilterByName, 1, const);
	PyAutoFunction_RegisterVoid(removePostFilter, 0);
	PyAutoFunction_Register(getNumLocalShaderOptions, int, 4, cons, bool, bool, bool);
	PyAutoFunction_RegisterVoid(setProjectionMatrix, 1, Matrix4);
	PyAutoFunction_Register(getViewport, Rectangle, 0);
	PyAutoFunction_Register(setProjectionMode, use, 1, ProjectionMode);
	PyAutoFunction_Register(getProjectionMode, use, 6, int, ORTHO_SIZE_LOCK_HEIGH, ORTHO_SIZE_LOCK_WIDT, ORTHO_SIZE_LOCK_WIDT, PERSPECTIVE_FO, PERSPECTIVE_FRUSTUM);
	PyAutoFunction_Register(getProjectionMode, int, 1, cons);
	PyAutoFunction_Register(ColorWithInts, Color, 4, int, int, int, int);
	PyAutoFunction_Register(ColorWithHex, Color, 1, unsigned);
	PyAutoFunction_Register(Color, return, 4, n, n, n, n);
	PyAutoFunction_Register(Color, return, 4, n, n, n, n);
	PyAutoFunction_Register(Color, return, 4, n, n, n, n);
	PyAutoFunction_RegisterVoid(setColorHex, 1, unsigned);
	PyAutoFunction_RegisterVoid(setColorHexRGB, 1, unsigned);
	PyAutoFunction_RegisterVoid(setColorHexFromString, 1, String);
	PyAutoFunction_RegisterVoid(setColorHexRGBFromString, 1, String);
	PyAutoFunction_RegisterVoid(setColorHSV, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setColorRGBA, 4, int, int, int, int);
	PyAutoFunction_RegisterVoid(setColorRGB, 3, int, int, int);
	PyAutoFunction_RegisterVoid(setColor, 4, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setColor, 1, const);
	PyAutoFunction_Register(blendColor, Color, 4, Color, int, Number, Color);
	PyAutoFunction_RegisterVoid(Random, 0);
	PyAutoFunction_Register(getBrightness, Number, 6, cons, const, const, Numbe, Numbe, Numbe);
	PyAutoFunction_RegisterVoid(loadConfig, 2, const, const);
	PyAutoFunction_RegisterVoid(saveConfig, 2, const, const);
	PyAutoFunction_RegisterVoid(setStringValue, 3, const, const, const);
	PyAutoFunction_RegisterVoid(setNumericValue, 3, const, const, Number);
	PyAutoFunction_Register(getNumericValue, Number, 2, const, const);
	PyAutoFunction_RegisterVoid(setBoolValue, 3, const, const, bool);
	PyAutoFunction_Register(getBoolValue, bool, 2, const, const);
	PyAutoFunction_Register(getThreadID, long, 0);
	PyAutoFunction_Register(Update, bool, 0);
	PyAutoFunction_RegisterVoid(Render, 1, bool);
	PyAutoFunction_Register(systemUpdate, bool, 1, bool);
	PyAutoFunction_RegisterVoid(enableMouse, 1, bool);
	PyAutoFunction_RegisterVoid(captureMouse, 1, bool);
	PyAutoFunction_RegisterVoid(setCursor, 2, int, int);
	PyAutoFunction_RegisterVoid(lockMutex, 1, CoreMute);
	PyAutoFunction_Register(getFPS, Number, 0);
	PyAutoFunction_RegisterVoid(Shutdown, 0);
	PyAutoFunction_Register(isFullscreen, bool, 1, return);
	PyAutoFunction_Register(getXRes, Number, 0);
	PyAutoFunction_Register(getYRes, Number, 0);
	PyAutoFunction_Register(getBackingXRes, Number, 1, return);
	PyAutoFunction_Register(getBackingYRes, Number, 1, return);
	PyAutoFunction_RegisterVoid(getScreenInfo, 3, in, in, in);
	PyAutoFunction_Register(getScreenWidth, int, 0);
	PyAutoFunction_Register(getScreenHeight, int, 0);
	PyAutoFunction_RegisterVoid(createFolder, 4, const, const, const, int);
	PyAutoFunction_Register(saveFilePicker, String, 10, st, false, 4, int, bool, bool, int, int, bool, int);
	PyAutoFunction_RegisterVoid(openURL, 1, String);
	PyAutoFunction_Register(getTicks, int, 1, **);
	PyAutoFunction_Register(getTicksFloat, double, 0);
	PyAutoFunction_RegisterVoid(setUserPointer, 3, voi, String, String);
	PyAutoFunction_Register(getUserHomeDirectory, String, 0);
	PyAutoFunction_RegisterVoid(makeApplicationMain, 1, CoreMute);
	PyAutoFunction_RegisterVoid(removeThread, 1, Threade);
	PyAutoFunction_Register(checkSpecialKeyEvents, bool, 1, PolyKEY);
	PyAutoFunction_RegisterVoid(gainFocus, 0);
	PyAutoFunction_RegisterVoid(updateCore, 0);
	PyAutoFunction_Register(getMousePosition, Vector2, 0);
	PyAutoFunction_Register(getKeyState, bool, 1, PolyKEY);
	PyAutoFunction_Register(getJoystickButtonState, bool, 2, int, int);
	PyAutoFunction_Register(getJoystickAxisValue, Number, 2, int, int);
	PyAutoFunction_Register(getMouseDelta, Vector2, 0);
	PyAutoFunction_Register(getMouseButtonState, bool, 1, int);
	PyAutoFunction_Register(getNumJoysticks, int, 0);
	PyAutoFunction_RegisterVoid(addJoystick, 1, unsigned);
	PyAutoFunction_RegisterVoid(removeJoystick, 1, unsigned);
	PyAutoFunction_RegisterVoid(joystickAxisMoved, 3, unsigned, float, unsigned);
	PyAutoFunction_RegisterVoid(joystickButtonDown, 2, unsigned, unsigned);
	PyAutoFunction_RegisterVoid(joystickButtonUp, 2, unsigned, unsigned);
	PyAutoFunction_RegisterVoid(mouseWheelUp, 1, int);
	PyAutoFunction_RegisterVoid(mouseWheelDown, 1, int);
	PyAutoFunction_RegisterVoid(setMouseButtonState, 3, int, bool, int);
	PyAutoFunction_RegisterVoid(setMousePosition, 3, int, int, int);
	PyAutoFunction_RegisterVoid(setKeyState, 4, PolyKEY, wchar_t, bool, int);
	PyAutoFunction_RegisterVoid(setDeltaPosition, 2, int, int);
	PyAutoFunction_RegisterVoid(touchesBegan, 3, TouchInfo, st, int);
	PyAutoFunction_RegisterVoid(touchesMoved, 3, TouchInfo, st, int);
	PyAutoFunction_RegisterVoid(touchesEnded, 3, TouchInfo, st, int);
	PyAutoFunction_RegisterVoid(clearInput, 0);
	PyAutoFunction_RegisterVoid(setInstance, 1, CoreService);
	PyAutoFunction_RegisterVoid(setRenderer, 1, Rendere);
	PyAutoFunction_RegisterVoid(Update, 1, int);
	PyAutoFunction_RegisterVoid(fixedUpdate, 0);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_RegisterVoid(setCore, 1, Cor);
	PyAutoFunction_RegisterVoid(setupBasicListeners, 0);
	PyAutoFunction_RegisterVoid(handleEvent, 1, Even);
	PyAutoFunction_RegisterVoid(installModule, 1, PolycodeModul);
	PyAutoFunction_RegisterVoid(setTexture, 2, Textur, int);
	PyAutoFunction_RegisterVoid(recreateFromTextures, 1, virtua);
	PyAutoFunction_Register(loadFromFile, bool, 1, const);
	PyAutoFunction_Register(getAsString, String, 2, int, int);
	PyAutoFunction_RegisterVoid(initEntity, 0);
	PyAutoFunction_RegisterVoid(Render, 1, *);
	PyAutoFunction_RegisterVoid(renderChildren, 0);
	PyAutoFunction_Register(Clone, call, 4, on, bool, bool, bool);
	PyAutoFunction_RegisterVoid(rebuildTransformMatrix, 0);
	PyAutoFunction_RegisterVoid(updateEntityMatrix, 0);
	PyAutoFunction_Register(getConcatenatedMatrix, Matrix4, 0);
	PyAutoFunction_Register(getConcatenatedMatrixRelativeTo, Matrix4, 1, Entit);
	PyAutoFunction_Register(getAnchorAdjustedMatrix, Matrix4, 0);
	PyAutoFunction_Register(getConcatenatedMatrix, as, 2, but, without);
	PyAutoFunction_Register(getLookAtMatrix, Matrix4, 2, const, const);
	PyAutoFunction_RegisterVoid(addChild, 1, Entit);
	PyAutoFunction_RegisterVoid(removeChild, 1, Entit);
	PyAutoFunction_RegisterVoid(moveChildUp, 1, Entit);
	PyAutoFunction_RegisterVoid(moveChildDown, 1, Entit);
	PyAutoFunction_RegisterVoid(moveChildTop, 1, Entit);
	PyAutoFunction_RegisterVoid(moveChildBottom, 1, Entit);
	PyAutoFunction_RegisterVoid(setParentEntity, 1, Entit);
	PyAutoFunction_Register(getNumChildren, int, 0);
	PyAutoFunction_RegisterVoid(setOwnsChildrenRecursive, 1, bool);
	PyAutoFunction_Register(getPosition, Vector3, 4, cons, use, Number, Number);
	PyAutoFunction_RegisterVoid(setPosition, 1, const);
	PyAutoFunction_RegisterVoid(setPositionX, 1, Number);
	PyAutoFunction_RegisterVoid(setPositionY, 1, Number);
	PyAutoFunction_RegisterVoid(Translate, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(Translate, 1, const);
	PyAutoFunction_RegisterVoid(setPositionZ, 1, Number);
	PyAutoFunction_RegisterVoid(setScaleX, 1, Number);
	PyAutoFunction_RegisterVoid(setScaleY, 1, Number);
	PyAutoFunction_RegisterVoid(setScaleZ, 1, Number);
	PyAutoFunction_RegisterVoid(Scale, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(Scale, 1, const);
	PyAutoFunction_RegisterVoid(setScale, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setScale, 1, const);
	PyAutoFunction_Register(getCompoundScale, Vector3, 1, cons);
	PyAutoFunction_RegisterVoid(setRotationEuler, 1, const);
	PyAutoFunction_RegisterVoid(setPitch, 1, Number);
	PyAutoFunction_RegisterVoid(setYaw, 1, Number);
	PyAutoFunction_RegisterVoid(setRoll, 1, Number);
	PyAutoFunction_RegisterVoid(Roll, 1, Number);
	PyAutoFunction_RegisterVoid(Yaw, 1, Number);
	PyAutoFunction_RegisterVoid(Pitch, 1, Number);
	PyAutoFunction_Register(getPitch, Number, 1, cons);
	PyAutoFunction_RegisterVoid(setHeight, 1, Number);
	PyAutoFunction_RegisterVoid(setDepth, 1, Number);
	PyAutoFunction_RegisterVoid(setRotationQuat, 4, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setRotationByQuaternion, 1, const);
	PyAutoFunction_Register(getRotationQuat, Quaternion, 2, cons, const);
	PyAutoFunction_Register(lookAt, see, 2, void, const);
	PyAutoFunction_Register(getCombinedColor, Color, 4, cons, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setColorInt, 4, int, int, int, int);
	PyAutoFunction_RegisterVoid(setColor, 1, Color);
	PyAutoFunction_RegisterVoid(setAnchorPoint, 1, const);
	PyAutoFunction_RegisterVoid(setAnchorPoint, 3, Number, Number, Number);
	PyAutoFunction_Register(getAnchorPoint, Vector3, 3, cons, int, int);
	PyAutoFunction_Register(onMouseUp, MouseEventResult, 3, const, int, int);
	PyAutoFunction_Register(onMouseMove, MouseEventResult, 2, const, int);
	PyAutoFunction_Register(onMouseWheelUp, MouseEventResult, 2, const, int);
	PyAutoFunction_Register(onMouseWheelDown, MouseEventResult, 2, const, int);
	PyAutoFunction_RegisterVoid(setUserData, 1, voi);
	PyAutoFunction_RegisterVoid(setBlendingMode, 1, int);
	PyAutoFunction_Register(getEntityProp, String, 1, const);
	PyAutoFunction_RegisterVoid(setEntityProp, 2, const, const);
	PyAutoFunction_RegisterVoid(setInverseY, 1, bool);
	PyAutoFunction_Register(getInverseY, bool, 0);
	PyAutoFunction_RegisterVoid(doUpdates, 0);
	PyAutoFunction_RegisterVoid(doFixedUpdates, 0);
	PyAutoFunction_Register(buildPositionMatrix, Matrix4, 0);
	PyAutoFunction_RegisterVoid(setRenderer, 1, Rendere);
	PyAutoFunction_Register(customHitDetection, bool, 5, const, the, will, this, false);
	PyAutoFunction_RegisterVoid(addTag, 1, String);
	PyAutoFunction_Register(getScreenPosition, Vector2, 3, const, const, const);
	PyAutoFunction_Register(getScreenPositionForMainCamera, Vector2, 0);
	PyAutoFunction_RegisterVoid(recalculateAABBAllChildren, 0);
	PyAutoFunction_RegisterVoid(recalculateAABB, 0);
	PyAutoFunction_Register(getWorldAABB, AABB, 0);
	PyAutoFunction_Register(getLocalBoundingBox, Vector3, 0);
	PyAutoFunction_RegisterVoid(setLocalBoundingBox, 1, const);
	PyAutoFunction_RegisterVoid(setLocalBoundingBox, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setLocalBoundingBoxX, 1, Number);
	PyAutoFunction_RegisterVoid(setLocalBoundingBoxY, 1, Number);
	PyAutoFunction_RegisterVoid(setLocalBoundingBoxZ, 1, Number);
	PyAutoFunction_Register(getEventCode, int, 1, cons);
	PyAutoFunction_RegisterVoid(setDispatcher, 1, EventDispatche);
	PyAutoStruct_Register(EventEntry);
	PyAutoStruct_RegisterMember(EventEntry, r, EventHandle);
	PyAutoStruct_RegisterMember(EventEntry, eventCode, int);
	PyAutoFunction_RegisterVoid(removeAllHandlers, 0);
	PyAutoFunction_RegisterVoid(removeAllHandlersForListener, 1, EventHandle);
	PyAutoFunction_Register(handleEvent, the, 2, metho, int);
	PyAutoFunction_RegisterVoid(addEventListenerUnique, 2, EventHandle, int);
	PyAutoFunction_Register(hasEventListener, bool, 2, EventHandle, int);
	PyAutoFunction_RegisterVoid(removeEventListener, 2, EventHandle, int);
	PyAutoFunction_RegisterVoid(__dispatchEvent, 2, Even, int);
	PyAutoFunction_RegisterVoid(dispatchEvent, 2, Even, int);
	PyAutoFunction_RegisterVoid(dispatchEventNoDelete, 2, Even, int);
	PyAutoFunction_RegisterVoid(addTexture, 2, const, Textur);
	PyAutoFunction_RegisterVoid(addCubemap, 2, const, Cubema);
	PyAutoFunction_Register(getFace, FT_Face, 0);
	PyAutoFunction_Register(isValid, bool, 1, cons);
	PyAutoFunction_Register(getFontName, String, 0);
	PyAutoFunction_Register(getFontPath, String, 0);
	PyAutoFunction_RegisterVoid(registerFont, 2, const, const);
	PyAutoFunction_Register(getNumFonts, int, 1, cons);
	PyAutoFunction_RegisterVoid(removeFontEntry, 2, FontEntr, bool);
	PyAutoFunction_Register(defined, if, 6, __APPLE_, Textur, Textur, Textur, Textur, Textur);
	PyAutoFunction_RegisterVoid(recreateFromTextures, 0);
	PyAutoFunction_Register(getTextureID, GLuint, 0);
	PyAutoFunction_Register(warning, pragma, 1, disabl);
	PyAutoFunction_Register(clampf, Number, 3, Number, Number, Number);
	PyAutoFunction_Register(Image, explicit, 1, const);
	PyAutoFunction_Register(loadImage, bool, 1, const);
	PyAutoFunction_Register(loadPNG, bool, 1, const);
	PyAutoFunction_Register(readTokens, TokenArray, 2, cha, const);
	PyAutoFunction_RegisterVoid(freeTokens, 1, TokenArray);
	PyAutoFunction_Register(loadHDR, bool, 1, const);
	PyAutoFunction_Register(saveImage, bool, 1, const);
	PyAutoFunction_Register(savePNG, bool, 1, const);
	PyAutoFunction_RegisterVoid(pasteImage, 6, Imag, int, int, int, Number, Color);
	PyAutoFunction_RegisterVoid(createEmpty, 2, int, int);
	PyAutoFunction_RegisterVoid(fill, 1, Color);
	PyAutoFunction_RegisterVoid(setPixel, 6, int, int, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setPixel, 3, int, int, Color);
	PyAutoFunction_Register(getPixel, Color, 2, int, int);
	PyAutoFunction_RegisterVoid(swap, 2, in, in);
	PyAutoFunction_RegisterVoid(drawLine, 5, int, int, int, int, Color);
	PyAutoFunction_RegisterVoid(moveBrushTo, 2, int, int);
	PyAutoFunction_RegisterVoid(moveBrush, 2, int, int);
	PyAutoFunction_RegisterVoid(drawLineTo, 3, int, int, Color);
	PyAutoFunction_RegisterVoid(fillRect, 5, int, int, int, int, Color);
	PyAutoFunction_RegisterVoid(perlinNoise, 2, int, bool);
	PyAutoFunction_RegisterVoid(fastBlur, 1, int);
	PyAutoFunction_RegisterVoid(fastBlurVert, 1, int);
	PyAutoFunction_RegisterVoid(fastBlurHor, 1, int);
	PyAutoFunction_Register(getBrushX, int, 2, cons, in);
	PyAutoFunction_RegisterVoid(premultiplyAlpha, 0);
	PyAutoFunction_Register(convertFloatToHFloat, hfloat, 1, float);
	PyAutoFunction_RegisterVoid(setPixelType, 1, int);
	PyAutoFunction_RegisterVoid(transformCoordinates, 2, in, in);
	PyAutoFunction_RegisterVoid(transformCoordinates, 4, in, in, in, in);
	PyAutoFunction_Register(getMousePosition, Vector2, 2, return, the);
	PyAutoFunction_RegisterVoid(clearData, 0);
	PyAutoFunction_RegisterVoid(setText, 1, const);
	PyAutoFunction_Register(getTextWidthForString, int, 1, const);
	PyAutoFunction_Register(getTextHeightForString, int, 1, const);
	PyAutoFunction_Register(getTextWidth, Number, 6, cons, not, so, you, unsigned, unsigned);
	PyAutoFunction_RegisterVoid(clearColors, 0);
	PyAutoFunction_Register(getColorForIndex, Color, 1, unsigned);
	PyAutoFunction_Register(getPremultiplyAlpha, bool, 2, cons, will);
	PyAutoFunction_RegisterVoid(setFont, 1, Fon);
	PyAutoFunction_RegisterVoid(setSize, 1, int);
	PyAutoFunction_Register(getSize, int, 2, cons, ANTIALIAS_NONE);
	PyAutoFunction_Register(getBaselineAdjust, int, 0);
	PyAutoFunction_Register(optionsChanged, bool, 0);
	PyAutoFunction_RegisterVoid(computeStringBbox, 2, GlyphDat, FT_BBo);
	PyAutoFunction_RegisterVoid(precacheGlyphs, 2, String, GlyphDat);
	PyAutoFunction_RegisterVoid(renderGlyphs, 1, GlyphDat);
	PyAutoFunction_RegisterVoid(drawGlyphBitmap, 4, FT_Bitma, unsigned, unsigned, Color);
	PyAutoFunction_Register(Material, explicit, 1, const);
	PyAutoFunction_RegisterVoid(addShader, 2, Shade, ShaderBindin);
	PyAutoFunction_RegisterVoid(addShaderAtIndex, 3, Shade, ShaderBindin, int);
	PyAutoFunction_Register(getNumShaders, int, 1, cons);
	PyAutoFunction_RegisterVoid(addShaderRenderTarget, 1, ShaderRenderTarge);
	PyAutoFunction_Register(getNumShaderRenderTargets, int, 0);
	PyAutoFunction_RegisterVoid(removeShaderRenderTarget, 1, int);
	PyAutoFunction_RegisterVoid(recreateRenderTarget, 1, ShaderRenderTarge);
	PyAutoFunction_RegisterVoid(recreateRenderTargets, 0);
	PyAutoFunction_RegisterVoid(handleEvent, 1, Even);
	PyAutoFunction_RegisterVoid(loadMaterial, 1, const);
	PyAutoFunction_RegisterVoid(setName, 1, const);
	PyAutoFunction_RegisterVoid(clearShaders, 0);
	PyAutoFunction_RegisterVoid(Update, 1, int);
	PyAutoFunction_RegisterVoid(deleteTexture, 1, Textur);
	PyAutoFunction_RegisterVoid(reloadTextures, 0);
	PyAutoFunction_RegisterVoid(reloadProgramsAndTextures, 0);
	PyAutoFunction_RegisterVoid(reloadPrograms, 0);
	PyAutoFunction_RegisterVoid(addShaderModule, 1, PolycodeShaderModul);
	PyAutoFunction_RegisterVoid(loadMaterialLibraryIntoPool, 2, ResourcePoo, const);
	PyAutoFunction_RegisterVoid(addMaterial, 1, Materia);
	PyAutoFunction_RegisterVoid(addShader, 1, Shade);
	PyAutoFunction_Register(getNumShaders, int, 0);
	PyAutoFunction_Register(Matrix4, inline, 16, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(identity, 2, memse, sizeo);
	PyAutoFunction_Register(rotateVector, Vector3, 3, const, v, v);
	PyAutoFunction_Register(getPosition, Vector3, 16, cons, n*, n*, n*, n*, n*, n*, n*, n*, n*, n*, n*, n*, n*, n*, n*);
	PyAutoFunction_Register(multVector, Vector3, 3, const, v, v);
	PyAutoFunction_Register(multVector, return, 1, v);
	PyAutoFunction_RegisterVoid(setPosition, 10, Number, Number, Number, Numbe, Numbe, angle_, angle_, tr_, tr_, angle_);
	PyAutoFunction_Register(transpose, Matrix4, 1, cons);
	PyAutoFunction_Register(Inverse, Matrix4, 2, cons, int);
	PyAutoStruct_Register(Vector4_struct);
	PyAutoStruct_RegisterMember(Vector4_struct, x, float);
	PyAutoStruct_RegisterMember(Vector4_struct, y, float);
	PyAutoStruct_RegisterMember(Vector4_struct, z, float);
	PyAutoStruct_RegisterMember(Vector4_struct, w, float);
	PyAutoStruct_Register(Vector3_struct);
	PyAutoStruct_RegisterMember(Vector3_struct, x, float);
	PyAutoStruct_RegisterMember(Vector3_struct, y, float);
	PyAutoStruct_RegisterMember(Vector3_struct, z, float);
	PyAutoStruct_Register(Vector2_struct);
	PyAutoStruct_RegisterMember(Vector2_struct, x, float);
	PyAutoStruct_RegisterMember(Vector2_struct, y, float);
	PyAutoFunction_Register(getVertexCount, int, 10, cons, arrayDirtyMap, positio, norma, et, Mes, Mes, Mes, Mes, Mes);
	PyAutoFunction_Register(Mesh, explicit, 1, const);
	PyAutoFunction_RegisterVoid(loadMesh, 1, const);
	PyAutoFunction_RegisterVoid(clearMesh, 0);
	PyAutoFunction_RegisterVoid(saveToFile, 7, const, bool, bool, bool, bool, bool, bool);
	PyAutoFunction_RegisterVoid(loadFromFile, 1, OSFIL);
	PyAutoFunction_RegisterVoid(saveToFile, 7, OSFIL, bool, bool, bool, bool, bool, bool);
	PyAutoFunction_Register(getVertexCount, int, 0);
	PyAutoFunction_RegisterVoid(createPlane, 2, Number, Number);
	PyAutoFunction_RegisterVoid(createVPlane, 2, Number, Number);
	PyAutoFunction_RegisterVoid(createCircle, 3, Number, Number, unsigned);
	PyAutoFunction_RegisterVoid(createLineCircle, 3, Number, Number, unsigned);
	PyAutoFunction_RegisterVoid(createTorus, 4, Number, Number, int, int);
	PyAutoFunction_RegisterVoid(createBox, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(createSphere, 3, Number, int, int);
	PyAutoFunction_RegisterVoid(createIcosphere, 2, Number, int);
	PyAutoFunction_RegisterVoid(createOctosphere, 2, Number, int);
	PyAutoFunction_RegisterVoid(createCylinder, 4, Number, Number, int, bool);
	PyAutoFunction_RegisterVoid(createCone, 3, Number, Number, int);
	PyAutoFunction_Register(recenterMesh, Vector3, 0);
	PyAutoFunction_RegisterVoid(setVertexAtOffset, 4, unsigned, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addVertexWithUVAndNormal, 8, Number, Number, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addTexCoord, 2, Number, Number);
	PyAutoFunction_RegisterVoid(addTexCoord2, 2, Number, Number);
	PyAutoFunction_RegisterVoid(addTangent, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addVertexWithUV, 5, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addVertex, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addNormal, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addNormal, 1, const);
	PyAutoFunction_RegisterVoid(addBoneAssignments, 8, Number, unsigned, Number, unsigned, Number, unsigned, Number, unsigned);
	PyAutoFunction_RegisterVoid(addColor, 4, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(addColor, 1, const);
	PyAutoFunction_Register(getVertexPosition, Vector3, 1, unsigned);
	PyAutoFunction_Register(getVertexPositionAtIndex, Vector3, 1, unsigned);
	PyAutoFunction_Register(getVertexTexCoord, Vector2, 1, unsigned);
	PyAutoFunction_Register(getVertexTexCoordAtIndex, Vector2, 1, unsigned);
	PyAutoFunction_RegisterVoid(setVertexBuffer, 1, VertexBuffe);
	PyAutoFunction_Register(getRadius, Number, 0);
	PyAutoFunction_RegisterVoid(calculateNormals, 0);
	PyAutoFunction_RegisterVoid(calculateTangents, 0);
	PyAutoFunction_Register(getMeshType, int, 0);
	PyAutoFunction_RegisterVoid(setMeshType, 1, int);
	PyAutoFunction_Register(getIndexGroupSize, int, 1, switc);
	PyAutoFunction_Register(hasVertexBuffer, bool, 3, return, the, unsigned);
	PyAutoFunction_RegisterVoid(addIndexedFace, 3, unsigned, unsigned, unsigned);
	PyAutoFunction_RegisterVoid(addIndexedFace, 4, unsigned, unsigned, unsigned, unsigned);
	PyAutoFunction_RegisterVoid(addIndex, 1, unsigned);
	PyAutoFunction_RegisterVoid(removeVertexRange, 2, unsigned, int);
	PyAutoFunction_RegisterVoid(removeFace, 1, unsigned);
	PyAutoFunction_Register(removeUnusedVertices, int, 0);
	PyAutoFunction_Register(getIndexCount, int, 0);
	PyAutoFunction_RegisterVoid(subdivideToRadius, 2, Number, int);
	PyAutoFunction_Register(calculateFaceTangent, Vector3, 6, const, const, const, const, const, const);
	PyAutoFunction_RegisterVoid(saveAsOBJ, 1, const);
	PyAutoFunction_RegisterVoid(normalizeBoneWeights, 0);
	PyAutoFunction_RegisterVoid(loadFromFileV2, 1, OSFIL);
	PyAutoFunction_RegisterVoid(loadFromFileLegacyV1, 1, OSFIL);
	PyAutoFunction_RegisterVoid(writeVertexBlock, 2, VertexDataArra, OSFIL);
	PyAutoFunction_RegisterVoid(writeIndexBlock, 2, IndexDataArra, OSFIL);
	PyAutoFunction_Register(getType, int, 1, return);
	PyAutoFunction_Register(acceptsExtension, bool, 9, const, const, TiXmlNod, String, String, String, Materia, ShaderBindin, unsigned);
	PyAutoFunction_Register(readNumber, bool, 2, String, Numbe);
	PyAutoFunction_Register(if, else, 3, chil, false, in);
	PyAutoFunction_Register(readInt, bool, 3, String, unsigne, in);
	PyAutoFunction_Register(readString, bool, 2, String, Strin);
	PyAutoFunction_Register(readBool, bool, 2, String, boo);
	PyAutoFunction_Register(ObjectEntry, new, 0);
	PyAutoFunction_Register(ObjectEntry, new, 0);
	PyAutoFunction_Register(ObjectEntry, new, 0);
	PyAutoFunction_Register(ObjectEntry, new, 0);
	PyAutoFunction_Register(ObjectEntry, new, 0);
	PyAutoFunction_Register(ObjectEntry, new, 0);
	PyAutoFunction_Register(getTypedName, String, 1, cons);
	PyAutoFunction_RegisterVoid(Clear, 0);
	PyAutoFunction_Register(loadFromXML, bool, 1, const);
	PyAutoFunction_Register(loadFromXMLString, bool, 1, const);
	PyAutoFunction_RegisterVoid(saveToXML, 1, const);
	PyAutoFunction_RegisterVoid(saveToBinary, 1, const);
	PyAutoFunction_Register(loadFromBinary, bool, 1, const);
	PyAutoFunction_RegisterVoid(createFromXMLElement, 2, TiXmlElemen, ObjectEntr);
	PyAutoFunction_Register(parseEntryFromFile, bool, 1, ObjectEntr);
	PyAutoFunction_Register(getKeyByIndex, String, 1, unsigned);
	PyAutoFunction_Register(readFile, bool, 0);
	PyAutoFunction_RegisterVoid(parseKeysFromObjectEntry, 1, ObjectEntr);
	PyAutoFunction_RegisterVoid(writeEntryToFile, 1, ObjectEntr);
	PyAutoFunction_Register(addKey, int, 1, const);
	PyAutoFunction_Register(getKeyIndex, int, 1, const);
	PyAutoFunction_Register(writeToFile, bool, 1, const);
	PyAutoFunction_RegisterVoid(setParticleCount, 1, unsigned);
	PyAutoFunction_Register(getParticleCount, int, 1, cons);
	PyAutoFunction_Register(getParticleLifetime, Number, 1, cons);
	PyAutoFunction_Register(getDirectionDeviation, Vector3, 1, cons);
	PyAutoFunction_Register(getEmitterSize, Vector3, 1, cons);
	PyAutoFunction_Register(getGravity, Vector3, 1, cons);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_RegisterVoid(updateParticles, 0);
	PyAutoFunction_RegisterVoid(rebuildParticles, 0);
	PyAutoFunction_RegisterVoid(triggerParticles, 1, bool);
	PyAutoFunction_RegisterVoid(enableParticleSystem, 1, bool);
	PyAutoFunction_RegisterVoid(setUseFloorPlane, 1, bool);
	PyAutoFunction_RegisterVoid(setFloorPlaneOffset, 1, Number);
	PyAutoFunction_RegisterVoid(setFloorDamping, 1, Number);
	PyAutoFunction_RegisterVoid(setParticlesInWorldSpace, 1, bool);
	PyAutoFunction_Register(getParticlesInWorldSpace, bool, 1, cons);
	PyAutoFunction_Register(getPerlinEnabled, bool, 1, cons);
	PyAutoFunction_RegisterVoid(setPerlinValue, 1, const);
	PyAutoFunction_Register(getPerlinValue, Vector3, 1, cons);
	PyAutoFunction_Register(getParticleType, int, 1, cons);
	PyAutoFunction_Register(getParticleSize, Number, 1, cons);
	PyAutoFunction_Register(getParticleRotationSpeed, Vector3, 1, cons);
	PyAutoFunction_Register(getParticleDirection, Vector3, 1, cons);
	PyAutoFunction_Register(getLoopParticles, bool, 1, cons);
	PyAutoFunction_Register(getNumSourceMeshes, int, 0);
	PyAutoFunction_RegisterVoid(removeSourceMeshAtIndex, 1, int);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_Register(Get2DTiledX, Number, 4, Number, Number, Number, *);
	PyAutoFunction_Register(Get, Number, 2, Number, Number);
	PyAutoFunction_Register(Get2D, Number, 2, Number, Number);
	PyAutoFunction_Register(Get3D, Number, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(init_perlin, 2, int, Number);
	PyAutoFunction_Register(perlin_noise_2D, Number, 1, Number);
	PyAutoFunction_Register(perlin_noise_3D, Number, 1, Number);
	PyAutoFunction_Register(noise1, Number, 1, Number);
	PyAutoFunction_Register(noise2, Number, 1, Number);
	PyAutoFunction_Register(noise3, Number, 1, Number);
	PyAutoFunction_RegisterVoid(normalize2, 1, Number);
	PyAutoFunction_RegisterVoid(normalize3, 1, Number);
	PyAutoFunction_RegisterVoid(init, 1, voi);
	PyAutoFunction_RegisterVoid(setFromMatrix, 1, const);
	PyAutoFunction_Register(Slerp, Quaternion, 4, Number, const, const, bool);
	PyAutoFunction_Register(Dot, Number, 1, const);
	PyAutoFunction_RegisterVoid(lookAt, 2, const, const);
	PyAutoFunction_RegisterVoid(createFromMatrix, 4, const, int, static, t);
	PyAutoFunction_Register(Squad, Quaternion, 6, Number, const, const, const, const, bool);
	PyAutoFunction_Register(Inverse, Quaternion, 1, cons);
	PyAutoFunction_RegisterVoid(set, 7, Number, Number, Number, Number, x*fInvNor, y*fInvNor, z*fInvNor);
	PyAutoFunction_Register(InvSqrt, Number, 1, Number);
	PyAutoFunction_RegisterVoid(fromAxes, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(fromAngleAxis, 2, const, const);
	PyAutoFunction_Register(Vector3, return, 5, atan, *, asi, atan, *);
	PyAutoFunction_RegisterVoid(createFromAxisAngle, 4, Number, Number, Number, Number);
	PyAutoFunction_Register(createMatrix, Matrix4, 2, cons, *);
	PyAutoFunction_Register(Vector3, return, 3, resul, resul, resul);
	PyAutoFunction_Register(interpolate, Quaternion, 2, Number, bool);
	PyAutoFunction_Register(interpolate, Quaternion, 3, unsigned, Number, bool);
	PyAutoFunction_RegisterVoid(generatePointsFromCurves, 4, BezierCurv, BezierCurv, BezierCurv, BezierCurv);
	PyAutoFunction_RegisterVoid(setRect, 4, Number, Number, Number, Number);
	PyAutoFunction_Register(Clipped, Rectangle, 1, const);
	PyAutoFunction_Register(getDataSize, int, 0);
	PyAutoFunction_Register(getDataSize, int, 0);
	PyAutoFunction_Register(getDataSize, int, 0);
	PyAutoFunction_Register(operator, bool, 2, LightInfo, LightInfo);
	PyAutoFunction_Register(Init, bool, 0);
	PyAutoFunction_RegisterVoid(Resize, 2, int, int);
	PyAutoFunction_RegisterVoid(EndRender, 0);
	PyAutoFunction_RegisterVoid(destroyTexture, 6, Textur, Textur, int, int, bool, unsigned);
	PyAutoFunction_RegisterVoid(bindFrameBufferTextureDepth, 1, Textur);
	PyAutoFunction_RegisterVoid(unbindFramebuffers, 0);
	PyAutoFunction_RegisterVoid(setViewportSize, 2, int, int);
	PyAutoFunction_RegisterVoid(resetViewport, 8, virtual, Number, Number, Number, bool, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setClearColor, 1, Color);
	PyAutoFunction_RegisterVoid(setAmbientColor, 3, Number, Number, Number);
	PyAutoFunction_RegisterVoid(clearScreen, 16, bool, bool, Number, Number, Number, Number, IndexDataArra, Number, Number, Color, Number, Number, Number, ShaderBindin, unsigned, bool);
	PyAutoFunction_RegisterVoid(clearShader, 2, virtual, bool);
	PyAutoFunction_RegisterVoid(billboardMatrixWithScale, 1, Vector3);
	PyAutoFunction_RegisterVoid(setTextureFilteringMode, 1, int);
	PyAutoFunction_RegisterVoid(setProjectionFromFrustum, 11, Number, Number, Number, Number, Number, Number, Number, Number, drawn, they, bool);
	PyAutoFunction_RegisterVoid(drawScreenQuad, 2, Number, Number);
	PyAutoFunction_Register(getYRes, int, 0);
	PyAutoFunction_Register(isScissorEnabled, bool, 0);
	PyAutoFunction_RegisterVoid(enableScissor, 1, bool);
	PyAutoFunction_RegisterVoid(setScissorBox, 1, Polycod);
	PyAutoFunction_Register(getScissorBox, Rectangle, 0);
	PyAutoFunction_RegisterVoid(setAnisotropyAmount, 1, Number);
	PyAutoFunction_Register(getAnisotropyAmount, Number, 0);
	PyAutoFunction_RegisterVoid(cullFrontFaces, 1, bool);
	PyAutoFunction_RegisterVoid(addLight, 15, int, const, const, int, const, const, Number, Number, Number, Number, Number, Number, bool, Matrix, Textur);
	PyAutoFunction_RegisterVoid(setExposureLevel, 1, Number);
	PyAutoFunction_Register(projectRayFrom2DCoordinate, Vector3, 8, Number, Number, const, const, const, const, const, const);
	PyAutoFunction_Register(getViewportWidth, Number, 0);
	PyAutoFunction_Register(getViewportHeight, Number, 0);
	PyAutoFunction_RegisterVoid(setViewportShift, 2, Number, Number);
	PyAutoFunction_RegisterVoid(setRendererShaderParams, 2, Shade, ShaderBindin);
	PyAutoFunction_RegisterVoid(addShaderModule, 1, PolycodeShaderModul);
	PyAutoFunction_Register(getProjectionMatrix, Matrix4, 5, virtual, Number, const, const, const);
	PyAutoFunction_Register(getNumPointLights, int, 2, return, Number);
	PyAutoFunction_Register(getBackingResolutionScaleX, Number, 0);
	PyAutoFunction_Register(getBackingResolutionScaleY, Number, 0);
	PyAutoFunction_RegisterVoid(setOverrideMaterial, 1, Materia);
	PyAutoFunction_RegisterVoid(pushVertexColor, 0);
	PyAutoFunction_RegisterVoid(popVertexColor, 0);
	PyAutoFunction_RegisterVoid(loadVertexColorIdentity, 0);
	PyAutoFunction_RegisterVoid(multiplyVertexColor, 1, const);
	PyAutoFunction_RegisterVoid(setRenderToGlobalFramebuffer, 1, bool);
	PyAutoFunction_RegisterVoid(reloadResource, 0);
	PyAutoFunction_Register(getResourceType, int, 1, cons);
	PyAutoFunction_RegisterVoid(setResourcePath, 1, const);
	PyAutoFunction_RegisterVoid(setFallbackPool, 1, ResourcePoo);
	PyAutoFunction_RegisterVoid(addResource, 1, Resourc);
	PyAutoFunction_RegisterVoid(removeResource, 1, Resourc);
	PyAutoFunction_Register(hasResource, bool, 1, Resourc);
	PyAutoFunction_Register(getName, String, 0);
	PyAutoFunction_RegisterVoid(setName, 1, const);
	PyAutoFunction_RegisterVoid(Update, 1, int);
	PyAutoFunction_RegisterVoid(checkForChangedFiles, 0);
	PyAutoFunction_RegisterVoid(addDirResource, 2, const, bool);
	PyAutoFunction_RegisterVoid(addArchive, 1, const);
	PyAutoFunction_RegisterVoid(removeArchive, 1, const);
	PyAutoFunction_RegisterVoid(parseTexturesIntoPool, 4, ResourcePoo, const, bool, const);
	PyAutoFunction_RegisterVoid(parseMaterialsIntoPool, 3, ResourcePoo, const, bool);
	PyAutoFunction_RegisterVoid(parseShadersIntoPool, 3, ResourcePoo, const, bool);
	PyAutoFunction_RegisterVoid(parseProgramsIntoPool, 3, ResourcePoo, const, bool);
	PyAutoFunction_RegisterVoid(parseCubemapsIntoPool, 3, ResourcePoo, const, bool);
	PyAutoFunction_RegisterVoid(parseOtherIntoPool, 3, ResourcePoo, const, bool);
	PyAutoFunction_RegisterVoid(addResourcePool, 1, ResourcePoo);
	PyAutoFunction_RegisterVoid(removeResourcePool, 1, ResourcePoo);
	PyAutoFunction_RegisterVoid(removeResource, 1, Resourc);
	PyAutoFunction_RegisterVoid(subscribeToResourcePool, 1, ResourcePoo);
	PyAutoFunction_RegisterVoid(unsubscibeFromResourcePool, 1, ResourcePoo);
	PyAutoFunction_RegisterVoid(Update, 1, int);
	PyAutoFunction_RegisterVoid(handleEvent, 1, Even);
	PyAutoFunction_RegisterVoid(addEntity, 1, Entit);
	PyAutoFunction_RegisterVoid(addChild, 1, Entit);
	PyAutoFunction_RegisterVoid(removeEntity, 1, Entit);
	PyAutoFunction_RegisterVoid(setActiveCamera, 1, Camer);
	PyAutoFunction_RegisterVoid(enableLighting, 1, bool);
	PyAutoFunction_RegisterVoid(enableFog, 1, bool);
	PyAutoFunction_RegisterVoid(setFogProperties, 5, int, Color, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setSceneType, 1, int);
	PyAutoFunction_RegisterVoid(fixedUpdate, 0);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(setVirtual, 1, bool);
	PyAutoFunction_Register(isVirtual, bool, 0);
	PyAutoFunction_Register(isEnabled, bool, 0);
	PyAutoFunction_RegisterVoid(setEnabled, 1, bool);
	PyAutoFunction_RegisterVoid(Render, 1, Camer);
	PyAutoFunction_RegisterVoid(RenderDepthOnly, 1, Camer);
	PyAutoFunction_RegisterVoid(setOverrideMaterial, 1, Materia);
	PyAutoFunction_RegisterVoid(handleEvent, 1, Even);
	PyAutoFunction_Register(projectRayFromCameraAndViewportCoordinate, Ray, 2, Camer, Vector2);
	PyAutoFunction_RegisterVoid(addLight, 1, SceneLigh);
	PyAutoFunction_RegisterVoid(removeLight, 1, SceneLigh);
	PyAutoFunction_Register(getNumLights, int, 0);
	PyAutoFunction_RegisterVoid(doVisibilityChecking, 1, bool);
	PyAutoFunction_Register(doesVisibilityChecking, bool, 0);
	PyAutoFunction_RegisterVoid(initScene, 2, int, bool);
	PyAutoFunction_RegisterVoid(setEntityVisibility, 2, Entit, Camer);
	PyAutoFunction_RegisterVoid(setEntityVisibilityBool, 2, Entit, bool);
	PyAutoFunction_Register(SceneEntityInstance, explicit, 1, Scen);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_RegisterVoid(clearInstance, 0);
	PyAutoFunction_RegisterVoid(parseObjectIntoCurve, 2, ObjectEntr, BezierCurv);
	PyAutoFunction_Register(loadFromFile, bool, 1, const);
	PyAutoFunction_RegisterVoid(applySceneMesh, 2, ObjectEntr, SceneMes);
	PyAutoFunction_RegisterVoid(linkResourcePool, 1, ResourcePoo);
	PyAutoFunction_Register(getNumLinkedResourePools, int, 0);
	PyAutoFunction_RegisterVoid(unlinkResourcePool, 1, ResourcePoo);
	PyAutoFunction_Register(hasLayerID, bool, 1, unsigned);
	PyAutoFunction_Register(getFileName, String, 1, cons);
	PyAutoFunction_RegisterVoid(setLayerVisibility, 1, bool);
	PyAutoFunction_RegisterVoid(reloadResource, 0);
	PyAutoFunction_Register(SceneImage, explicit, 1, const);
	PyAutoFunction_Register(SceneImage, explicit, 1, Imag);
	PyAutoFunction_Register(SceneImage, explicit, 1, Textur);
	PyAutoFunction_Register(SceneImageWithImage, SceneImage*, 1, Imag);
	PyAutoFunction_Register(SceneImageWithTexture, SceneImage*, 1, Textur);
	PyAutoFunction_RegisterVoid(applyClone, 8, Entit, bool, bool, Number, Number, Number, Number, Number);
	PyAutoFunction_Register(getText, String, 0);
	PyAutoFunction_RegisterVoid(setLabelActualHeight, 1, Number);
	PyAutoFunction_Register(getLabelActualHeight, Number, 0);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_Register(getTextWidthForString, int, 1, String);
	PyAutoFunction_RegisterVoid(setText, 1, const);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_Register(getIntensity, Number, 1, cons);
	PyAutoFunction_RegisterVoid(setAttenuation, 3, Number, Number, Number);
	PyAutoFunction_Register(getConstantAttenuation, Number, 1, cons);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_RegisterVoid(setSpecularLightColor, 9, Number, Number, Number, Number, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(setSpotlightProperties, 5, Number, Number, the, enables, unsigned);
	PyAutoFunction_RegisterVoid(setShadowMapFOV, 1, Number);
	PyAutoFunction_Register(getShadowMapFOV, Number, 1, cons);
	PyAutoFunction_Register(getLightImportance, int, 1, cons);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_Register(getWorldPointAt, Vector3, 1, Number);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_RegisterVoid(setStart, 1, Vector3);
	PyAutoFunction_RegisterVoid(setEnd, 1, Vector3);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(initLine, 0);
	PyAutoFunction_RegisterVoid(addScene, 1, Scen);
	PyAutoFunction_RegisterVoid(removeScene, 1, Scen);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(fixedUpdate, 0);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_RegisterVoid(renderVirtual, 0);
	PyAutoFunction_RegisterVoid(registerRenderTexture, 1, SceneRenderTextur);
	PyAutoFunction_RegisterVoid(unregisterRenderTexture, 1, SceneRenderTextur);
	PyAutoFunction_RegisterVoid(setRenderer, 1, Rendere);
	PyAutoFunction_RegisterVoid(updateRenderTextures, 1, Scen);
	PyAutoFunction_Register(SceneMesh, explicit, 1, const);
	PyAutoFunction_Register(SceneMesh, explicit, 1, int);
	PyAutoFunction_Register(SceneMesh, explicit, 1, Mes);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_RegisterVoid(loadTexture, 1, const);
	PyAutoFunction_RegisterVoid(loadTextureFromImage, 1, Imag);
	PyAutoFunction_RegisterVoid(setTexture, 1, Textur);
	PyAutoFunction_RegisterVoid(clearMaterial, 0);
	PyAutoFunction_RegisterVoid(setMaterial, 1, Materia);
	PyAutoFunction_RegisterVoid(setMaterialByName, 2, const, ResourcePoo);
	PyAutoFunction_RegisterVoid(setMesh, 1, Mes);
	PyAutoFunction_RegisterVoid(setSkeleton, 1, Skeleto);
	PyAutoFunction_RegisterVoid(renderMeshLocally, 0);
	PyAutoFunction_RegisterVoid(cacheToVertexBuffer, 1, bool);
	PyAutoFunction_RegisterVoid(setLineWidth, 1, Number);
	PyAutoFunction_Register(getFilename, String, 0);
	PyAutoFunction_RegisterVoid(setFilename, 1, String);
	PyAutoFunction_RegisterVoid(loadFromFile, 1, String);
	PyAutoFunction_Register(customHitDetection, bool, 1, const);
	PyAutoFunction_RegisterVoid(setPrimitiveOptions, 6, int, Number, Number, Number, Number, Number);
	PyAutoFunction_RegisterVoid(recreatePrimitive, 0);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_RegisterVoid(resizeRenderTexture, 2, int, int);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_RegisterVoid(setLoopOnLoad, 1, bool);
	PyAutoFunction_Register(getLoopOnLoad, bool, 0);
	PyAutoFunction_RegisterVoid(setName, 1, String);
	PyAutoFunction_Register(getName, String, 1, cons);
	PyAutoFunction_Register(getNumFrameIDs, int, 0);
	PyAutoFunction_Register(getFrameIDAtIndex, int, 1, unsigned);
	PyAutoFunction_RegisterVoid(insertFrame, 2, unsigned, unsigned);
	PyAutoFunction_Register(setNewFrameIDs, POLYIGNORE, 1, st);
	PyAutoFunction_RegisterVoid(removeFrameByIndex, 1, unsigned);
	PyAutoFunction_Register(removeFrameIndices, POLYIGNORE, 1, st);
	PyAutoFunction_RegisterVoid(clearFrames, 0);
	PyAutoFunction_RegisterVoid(setPixelsPerUnit, 1, Number);
	PyAutoFunction_Register(getPixelsPerUnit, Number, 0);
	PyAutoFunction_RegisterVoid(rebuildStateMeshes, 0);
	PyAutoFunction_RegisterVoid(setStateFPS, 1, Number);
	PyAutoFunction_Register(getStateFPS, Number, 0);
	PyAutoFunction_Register(getLargestFrameBoundingBox, Vector3, 1, cons);
	PyAutoFunction_Register(getBoundingBox, Vector2, 0);
	PyAutoFunction_Register(getSpriteOffset, Vector2, 0);
	PyAutoFunction_RegisterVoid(setSpriteOffset, 1, const);
	PyAutoFunction_Register(getName, String, 0);
	PyAutoFunction_RegisterVoid(setName, 1, String);
	PyAutoFunction_RegisterVoid(addSpriteState, 1, SpriteStat);
	PyAutoFunction_RegisterVoid(removeSpriteState, 1, SpriteStat);
	PyAutoFunction_Register(getNumStates, int, 0);
	PyAutoFunction_RegisterVoid(setParentSpritSet, 1, SpriteSe);
	PyAutoFunction_RegisterVoid(setTexture, 1, Textur);
	PyAutoFunction_RegisterVoid(addSpriteEntry, 1, Sprit);
	PyAutoFunction_Register(getNumSpriteEntries, int, 1, cons);
	PyAutoFunction_RegisterVoid(loadSpriteSet, 1, String);
	PyAutoFunction_RegisterVoid(addSpriteFrame, 2, const, bool);
	PyAutoFunction_Register(getNumFrames, int, 1, cons);
	PyAutoFunction_RegisterVoid(setSpriteFrame, 1, const);
	PyAutoFunction_RegisterVoid(clearFrames, 0);
	PyAutoFunction_RegisterVoid(createGridFrames, 3, Number, Number, const);
	PyAutoFunction_RegisterVoid(createFramesFromIslands, 2, unsigned, const);
	PyAutoFunction_RegisterVoid(applyClone, 3, Entit, bool, bool);
	PyAutoFunction_RegisterVoid(handleEvent, 1, Even);
	PyAutoFunction_RegisterVoid(setSpriteSet, 1, SpriteSe);
	PyAutoFunction_RegisterVoid(setSpriteByName, 1, String);
	PyAutoFunction_RegisterVoid(setCurrentFrame, 1, unsigned);
	PyAutoFunction_Register(getCurrentFrame, int, 0);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(Render, 0);
	PyAutoFunction_Register(getSpriteBoundingBox, Vector3, 1, cons);
	PyAutoFunction_Register(isPaused, bool, 0);
	PyAutoFunction_RegisterVoid(setSprite, 1, Sprit);
	PyAutoFunction_RegisterVoid(setSpriteState, 3, SpriteStat, unsigned, bool);
	PyAutoFunction_RegisterVoid(setSpriteStateByName, 3, String, unsigned, bool);
	PyAutoFunction_Register(getStartOnRandomFrame, bool, 0);
	PyAutoFunction_RegisterVoid(setStartOnRandomFrame, 1, bool);
	PyAutoStruct_Register(TextureBinding);
	PyAutoStruct_RegisterMember(TextureBinding, e, Textur);
	PyAutoStruct_RegisterMember(TextureBinding, name, String);
	PyAutoStruct_Register(CubemapBinding);
	PyAutoStruct_RegisterMember(CubemapBinding, p, Cubema);
	PyAutoStruct_RegisterMember(CubemapBinding, name, String);
	PyAutoFunction_Register(ShaderProgram, explicit, 1, int);
	PyAutoFunction_RegisterVoid(reloadProgram, 1, static);
	PyAutoFunction_Register(Shader, explicit, 1, int);
	PyAutoFunction_Register(getType, int, 1, cons);
	PyAutoFunction_RegisterVoid(reload, 1, int);
	PyAutoFunction_RegisterVoid(setVertexProgram, 1, ShaderProgra);
	PyAutoFunction_Register(getNumber, Number, 0);
	PyAutoFunction_Register(getVector2, Vector2, 0);
	PyAutoFunction_Register(getVector3, Vector3, 0);
	PyAutoFunction_Register(getMatrix4, Matrix4, 0);
	PyAutoFunction_Register(getColor, Color, 0);
	PyAutoFunction_RegisterVoid(setNumber, 1, Number);
	PyAutoFunction_RegisterVoid(setVector2, 1, Vector2);
	PyAutoFunction_RegisterVoid(setVector3, 1, Vector3);
	PyAutoFunction_RegisterVoid(setMatrix4, 1, Matrix4);
	PyAutoFunction_RegisterVoid(setColor, 1, Color);
	PyAutoFunction_RegisterVoid(setParamValueFromString, 2, int, String);
	PyAutoFunction_RegisterVoid(copyTo, 1, ShaderBindin);
	PyAutoFunction_RegisterVoid(clearTexture, 1, const);
	PyAutoFunction_RegisterVoid(clearCubemap, 1, const);
	PyAutoFunction_RegisterVoid(addTexture, 2, const, Textur);
	PyAutoFunction_RegisterVoid(addCubemap, 2, const, Cubema);
	PyAutoFunction_Register(getNumLocalParams, int, 0);
	PyAutoFunction_RegisterVoid(addRenderTargetBinding, 1, RenderTargetBindin);
	PyAutoFunction_RegisterVoid(removeRenderTargetBinding, 1, RenderTargetBindin);
	PyAutoFunction_Register(getNumRenderTargetBindings, int, 0);
	PyAutoFunction_Register(getNumInTargetBindings, int, 0);
	PyAutoFunction_Register(getNumColorTargetBindings, int, 0);
	PyAutoFunction_Register(getNumDepthTargetBindings, int, 0);
	PyAutoFunction_Register(getNumOutTargetBindings, int, 0);
	PyAutoFunction_RegisterVoid(Play, 1, bool);
	PyAutoFunction_RegisterVoid(Stop, 0);
	PyAutoFunction_RegisterVoid(Update, 1, Number);
	PyAutoFunction_RegisterVoid(Reset, 0);
	PyAutoFunction_RegisterVoid(setSpeed, 1, Number);
	PyAutoFunction_RegisterVoid(addBoneTrack, 1, BoneTrac);
	PyAutoFunction_RegisterVoid(Play, 1, bool);
	PyAutoFunction_RegisterVoid(Stop, 0);
	PyAutoFunction_RegisterVoid(Reset, 0);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(setSpeed, 1, Number);
	PyAutoFunction_RegisterVoid(setWeight, 1, Number);
	PyAutoFunction_Register(getWeight, Number, 1, cons);
	PyAutoFunction_RegisterVoid(loadSkeleton, 1, const);
	PyAutoFunction_RegisterVoid(playAnimationByName, 4, const, Number, bool, bool);
	PyAutoFunction_RegisterVoid(playAnimation, 4, SkeletonAnimatio, Number, bool, bool);
	PyAutoFunction_RegisterVoid(setBaseAnimationByName, 1, const);
	PyAutoFunction_RegisterVoid(setBaseAnimation, 1, SkeletonAnimatio);
	PyAutoFunction_RegisterVoid(stopAllAnimations, 0);
	PyAutoFunction_RegisterVoid(addAnimation, 2, const, const);
	PyAutoFunction_RegisterVoid(stopAnimationByName, 1, const);
	PyAutoFunction_RegisterVoid(stopAnimation, 1, SkeletonAnimatio);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(bonesVisible, 1, bool);
	PyAutoFunction_Register(defined, if, 2, __APPLE_, bool);
	PyAutoFunction_RegisterVoid(loadFile, 2, String, bool);
	PyAutoFunction_RegisterVoid(reloadProperties, 0);
	PyAutoFunction_RegisterVoid(Play, 1, bool);
	PyAutoFunction_RegisterVoid(Stop, 0);
	PyAutoFunction_RegisterVoid(setVolume, 1, Number);
	PyAutoFunction_Register(getVolume, Number, 0);
	PyAutoFunction_RegisterVoid(setPitch, 1, Number);
	PyAutoFunction_Register(getPitch, Number, 0);
	PyAutoFunction_Register(isPlaying, bool, 0);
	PyAutoFunction_RegisterVoid(setIsPositional, 1, bool);
	PyAutoFunction_RegisterVoid(setSoundPosition, 1, Vector3);
	PyAutoFunction_RegisterVoid(setSoundVelocity, 1, Vector3);
	PyAutoFunction_RegisterVoid(setSoundDirection, 1, Vector3);
	PyAutoFunction_RegisterVoid(setOffset, 1, int);
	PyAutoFunction_Register(getFileName, String, 0);
	PyAutoFunction_Register(getPlaybackDuration, Number, 0);
	PyAutoFunction_Register(getPlaybackTime, Number, 0);
	PyAutoFunction_RegisterVoid(seekTo, 1, Number);
	PyAutoFunction_Register(getOffset, int, 0);
	PyAutoFunction_Register(getSampleLength, int, 0);
	PyAutoFunction_RegisterVoid(setPositionalProperties, 2, Number, Number);
	PyAutoFunction_RegisterVoid(setReferenceDistance, 1, Number);
	PyAutoFunction_RegisterVoid(setMaxDistance, 1, Number);
	PyAutoFunction_Register(getReferenceDistance, Number, 0);
	PyAutoFunction_Register(getMaxDistance, Number, 0);
	PyAutoFunction_Register(loadBytes, ALuint, 6, const, int, int, ALsizei, int, bool);
	PyAutoFunction_Register(loadWAV, ALuint, 2, const, bool);
	PyAutoFunction_Register(loadOGG, ALuint, 2, const, bool);
	PyAutoFunction_Register(GenSource, ALuint, 1, ALuint);
	PyAutoFunction_Register(GenSource, ALuint, 0);
	PyAutoFunction_Register(checkALError, ALenum, 1, const);
	PyAutoFunction_RegisterVoid(soundError, 1, const);
	PyAutoFunction_RegisterVoid(soundCheck, 2, bool, const);
	PyAutoFunction_Register(readByte32, long, 1, const);
	PyAutoFunction_Register(readByte16, short, 1, const);
	PyAutoFunction_Register(defined, if, 1, __APPLE_);
	PyAutoFunction_RegisterVoid(setListenerPosition, 1, Vector3);
	PyAutoFunction_RegisterVoid(setListenerOrientation, 2, Vector3, Vector3);
	PyAutoFunction_RegisterVoid(initAL, 0);
	PyAutoFunction_Register(recordSound, bool, 2, unsigned, unsigned);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(setGlobalVolume, 1, Number);
	PyAutoFunction_RegisterVoid(utf8toWStr, 2, WSt, const);
	PyAutoFunction_RegisterVoid(wstrToUtf8, 2, St, const);
	PyAutoFunction_Register(size, size_t, 1, cons);
	PyAutoFunction_Register(length, size_t, 1, cons);
	PyAutoFunction_Register(substr, String, 2, size_t, size_t);
	PyAutoFunction_Register(find_last_of, size_t, 3, const, size_t, po);
	PyAutoFunction_Register(find_first_of, size_t, 3, const, size_t, po);
	PyAutoFunction_Register(String, return, 1, content);
	PyAutoFunction_Register(String, return, 1, content);
	PyAutoFunction_Register(toLowerCase, String, 3, cons, const, int);
	PyAutoFunction_Register(toNumber, Number, 0);
	PyAutoFunction_Register(toInteger, int, 0);
	PyAutoFunction_Register(IntToString, String, 1, int);
	PyAutoFunction_Register(getDataSizeWithEncoding, see, 1, const);
	PyAutoFunction_Register(getDataWithEncoding, see, 1, void);
	PyAutoFunction_Register(getDataSizeWithEncoding, size_t, 2, int, int);
	PyAutoFunction_Register(isNumber, bool, 0);
	PyAutoFunction_Register(String, return, 1, Strin);
	PyAutoFunction_Register(String, return, 1, Strin);
	PyAutoFunction_RegisterVoid(setFont, 1, FontGlyphSheet*);
	PyAutoFunction_RegisterVoid(setText, 1, const);
	PyAutoFunction_RegisterVoid(rebuild, 0);
	PyAutoFunction_RegisterVoid(reloadResource, 0);
	PyAutoFunction_RegisterVoid(setTextureData, 1, cha);
	PyAutoFunction_RegisterVoid(updateScroll, 1, int);
	PyAutoFunction_RegisterVoid(Pause, 1, bool);
	PyAutoFunction_Register(isPaused, bool, 0);
	PyAutoFunction_Register(getTicks, int, 0);
	PyAutoFunction_RegisterVoid(Update, 1, unsigned);
	PyAutoFunction_RegisterVoid(Reset, 0);
	PyAutoFunction_Register(hasElapsed, bool, 0);
	PyAutoFunction_Register(getElapsedf, Number, 0);
	PyAutoFunction_RegisterVoid(setTimerInterval, 1, int);
	PyAutoFunction_RegisterVoid(removeTimer, 1, Time);
	PyAutoFunction_RegisterVoid(addTimer, 1, Time);
	PyAutoFunction_RegisterVoid(Update, 0);
	PyAutoFunction_RegisterVoid(set, 2, Number, Number);
	PyAutoFunction_Register(Vector2, return, 2, v, v);
	PyAutoFunction_Register(distance, Number, 1, const);
	PyAutoFunction_Register(Vector2, return, 2, *, *);
	PyAutoFunction_Register(Vector2, return, 2, *, *);
	PyAutoFunction_Register(Vector2, return, 2, v, v);
	PyAutoFunction_Register(Vector2, return, 0);
	PyAutoFunction_Register(sqrtf, return, 1, *);
	PyAutoFunction_Register(dot, Number, 3, const, theta, theta);
	PyAutoFunction_RegisterVoid(Normalize, 0);
	PyAutoFunction_RegisterVoid(set, 3, Number, Number, Number);
	PyAutoFunction_Register(Vector3, return, 3, v, v, v);
	PyAutoFunction_Register(distance, Number, 1, const);
	PyAutoFunction_Register(Vector3, return, 3, *, *, *);
	PyAutoFunction_Register(Vector3, return, 3, *, *, *);
	PyAutoFunction_Register(Vector3, return, 3, v, v, v);
	PyAutoFunction_Register(Vector3, return, 0);
	PyAutoFunction_Register(angleBetween, Number, 1, const);
	PyAutoFunction_Register(acosf, return, 0);
	PyAutoFunction_Register(sqrtf, return, 1, *);
	PyAutoFunction_Register(length, than, 1, for);
	PyAutoFunction_Register(setLength, Vector3, 1, const);
	PyAutoFunction_Register(dot, Number, 3, const, *, *);
	PyAutoFunction_RegisterVoid(Normalize, 0);
	PyAutoFunction_RegisterVoid(set, 4, Number, Number, Number, Number);
	PyAutoFunction_Register(Vector4, return, 4, v, v, v, v);
	PyAutoFunction_Register(Vector4, return, 4, *, *, *, *);
	PyAutoFunction_Register(Vector4, return, 4, *, *, *, *);
	PyAutoFunction_Register(Vector4, return, 4, v, v, v, v);
	PyAutoFunction_Register(Vector4, return, 0);
	PyAutoStruct_Register(rgbe_header_info);
	PyAutoStruct_RegisterMember(rgbe_header_info, valid, int);
	PyAutoStruct_RegisterMember(rgbe_header_info, indicate, *);
	PyAutoStruct_RegisterMember(rgbe_header_info, listed, *);
	PyAutoStruct_RegisterMember(rgbe_header_info, image, *);
	PyAutoStruct_RegisterMember(rgbe_header_info, a, *);
	PyAutoFunction_Register(RGBE_WriteHeader, int, 4, FIL, int, int, rgbe_header_inf);
	PyAutoFunction_Register(RGBE_ReadHeader, int, 4, FIL, in, in, rgbe_header_inf);
	PyAutoFunction_Register(RGBE_WritePixels, int, 3, FIL, floa, int);
	PyAutoFunction_Register(RGBE_ReadPixels, int, 3, FIL, floa, int);
	PyAutoFunction_Register(RGBE_WritePixels_RLE, int, 4, FIL, floa, int, int);
	PyAutoFunction_Register(RGBE_ReadPixels_RLE, int, 4, FIL, floa, int, int);

	PyAutoC_Finalize();
	Py_Finalize();
	return 0;
}
